export function useRandomQuotes() {
    const punchlines = ref([
        "En mode hardcore, même les PNJ ne nous font pas de cadeaux.",
        "Sauvegarder ? C'est pour ceux qui doutent de leurs pouvoirs.",
        "Je vis, je meurs, je me respawn à l'infini.",
        "Qui a besoin de la réalité quand on a triple saut ?",
        "Les vrais héros connaissent le code Konami par cœur.",
        "Le dernier niveau ? Un simple échauffement pour moi.",
        "Les pixels, c'est comme le chocolat, ça rend heureux.",
        "Rien ne vaut le bruit d'un achievement qui se débloque.",
        "Le game over, c'est juste un nouveau début.",
        "En quête d'épées légendaires et de donjons cachés.",
        "Un bon jeu a toujours une place dans mon disque dur.",
        "La gravité ? Juste une option dans mes jeux préférés.",
        "Mes doigts dansent sur le clavier, une symphonie de victoires.",
        "Si la vie avait un bouton reset, je jouerais différemment.",
        "Dans le royaume des pixels, le joystick est roi.",
        "Chasseur de trophées professionnel, et fier de l'être.",
        "Jouer c'est croire en l'impossible, encore et encore.",
        "La seule peur que j'ai, c'est la batterie faible.",
        "Pourquoi rêver sa vie quand on peut vivre ses rêves en jeu ?",
        "Les boss difficiles font les victoires savoureuses.",
        "Quand je joue, je ne vieillis pas. Je monte de niveau.",
        "Une nuit blanche ? Non, une quête épique.",
        "Les héros ne meurent jamais, ils respawnent.",
        "Ma console, mon royaume ; ma manette, mon sceptre.",
        "Chaque partie est une histoire à raconter.",
        "La vraie quête commence quand la console s'éteint.",
        "Le vrai trésor était les amis faits en chemin.",
        "N'éteins jamais la console sur une défaite.",
        "La seule chose que je farme, c'est la gloire.",
        "Les pixels d'aujourd'hui sont les souvenirs de demain.",
        "Ma stratégie ? Appuyer sur tous les boutons et espérer.",
        "Un vrai gamer connaît la valeur d'une bonne pause.",
        "Les jeux ne se terminent pas ; ils se recommencent.",
        "Si tu peux le rêver, tu peux le jouer.",
        "Les mondes virtuels, mes destinations préférées.",
        "Un bon jeu est comme un bon livre, impossible à lâcher.",
        "Les légendes ne meurent jamais, elles sont juste en mode pause.",
        "Jouer, c'est explorer des mondes sans quitter son salon.",
        "Les meilleurs voyages sont ceux faits sur console.",
        "Ma manette, une extension de ma volonté.",
        "Dans chaque jeu, une leçon ; dans chaque victoire, une histoire.",
        "Seul face à l'écran, ensemble dans l'aventure.",
        "Chaque niveau passé, une fierté gagnée.",
        "Les défaites d'aujourd'hui sont les victoires de demain.",
        "On ne perd jamais ; on apprend ou on gagne.",
        "La magie du jeu, c'est de transformer l'ordinaire en extraordinaire.",
        "Gamer un jour, gamer toujours.",
        "Les véritables aventures commencent au-delà de la zone de confort... du canapé.",
        "Quand je joue, le monde réel est en mode pause.",
        "Les quêtes secondaires ? Ma spécialité, surtout pour éviter la principale.",
        "Les héros portent des casques, pas des capes. Du moins, dans mes jeux.",
        "Plus de mana ? C'est l'heure de la tactique au corps à corps.",
        "Perdre c'est apprendre. Gagner, c'est enseigner.",
        "La seule chose que je rage quit, c'est mon réveil le matin.",
        "L'IA n'est pas de taille face à la ruse d'un joueur malin.",
        "Les graphismes vieillissent, le plaisir de jouer reste éternel.",
        "Les meilleurs loots sont ceux qu'on partage avec les amis.",
        "Un bon jeu te fait oublier que tu n'as pas bougé depuis 8 heures.",
        "Les cartes graphiques chauffent, les cœurs des gamers aussi.",
        "La seule limite est celle de l'imagination... et de la RAM.",
        "Les jeux nous enseignent que même un petit personnage peut sauver le monde.",
        "Si tu n'as jamais crié sur un écran, tu n'as jamais vraiment joué.",
        "Pourquoi aller à l'école quand on peut aller à l'école de sorcellerie en jeu ?",
        "Les Easter eggs, le véritable but de tout explorateur virtuel.",
        "Une pause café ? Non, une pause jeu.",
        "Les guerriers ne meurent pas. Ils retournent au dernier checkpoint.",
        "Un bon gamer connaît ses limites, un grand les dépasse.",
        "Rien de tel qu'une quête épique pour oublier une journée banale.",
        "Le son du level up est ma mélodie préférée.",
        "Pourquoi attendre le futur ? Je l'ai déjà sauvé dix fois.",
        "Les monstres sous mon lit ont peur de ceux dans mes jeux.",
        "Dans chaque pixel, une aventure. Dans chaque jeu, une vie.",
        "Je ne suis pas perdu ; je suis en exploration exhaustive.",
        "La fin du jeu ? Ce n'est que le début de la légende.",
        "Le véritable game over, c'est d'arrêter de jouer.",
        "Pourquoi dormir quand on peut explorer des galaxies ?",
        "Le chaos n'est qu'une partie de niveau non maîtrisée... pour l'instant.",
        "Les véritables défis sont ceux qu'on trouve après avoir fini le jeu.",
        "Un vrai gamer trouve toujours un chemin, même dans un labyrinthe sans fin.",
        "Les jeux vidéo n'ont pas de fin. Juste des pauses prolongées.",
        "Un bon jeu est une porte vers un autre univers.",
        "Rien n'est plus satisfaisant que de battre un boss du premier coup.",
        "Je ne procrastine pas. Je perfectionne mes compétences de jeu.",
        "Les héros virtuels enseignent les plus grandes leçons de courage.",
        "Dans la vie, comme dans le jeu, chaque choix ouvre de nouveaux chemins.",
        "Les contrôleurs sont le véritable lien entre deux mondes.",
        "Le véritable amour, c'est partager sa sauvegarde avec quelqu'un.",
        "Chaque jeu terminé est une histoire qui reste à jamais.",
        "Les jeux nous rappellent que l'impossible n'est qu'une question de stratégie.",
        "Les meilleurs compagnons de quête sont souvent numériques.",
        "Le son de l'item rare qui tombe, musique pour mes oreilles.",
        "Les vrais explorateurs ne craignent pas le game over.",
        "La stratégie est l'art de faire d'une partie perdue, une légende.",
        "Dans le jeu de la vie, choisis ta classe avec sagesse.",
        "Les jeux vidéo, c'est l'art de transformer une journée ordinaire en aventure extraordinaire.",
        "Je ne joue pas pour échapper à la réalité, mais pour la redéfinir.",
        "Explorer Hyrule, c'est accepter de se perdre pour mieux se retrouver.",
        "Attrapez-les tous ! Même si ça signifie transformer votre salon en arène Pokémon.",
        "Dans le Nether ou sur Terre, chaque construction Minecraft porte notre empreinte.",
        "Face à un Colosse, on réalise la grandeur de notre quête.",
        "Lorsque le destin de l'univers repose sur vos épaules, vous rejouez Mass Effect.",
        "Un dragon dans Skyrim ? Un bon prétexte pour ne pas aller travailler.",
        "Survivre à Raccoon City requiert plus qu'une bonne arme ; il faut du papier toilette.",
        "Se perdre dans les dédales de The Binding of Isaac, c'est trouver des trésors inattendus.",
        "Dans Animal Crossing, le plus gros crédit n'est pas à la banque, mais auprès de nos voisins.",
        "Être un héros de Final Fantasy, c'est accepter de porter des épées démesurées.",
        "Courir dans les rues de Liberty City me donne envie de respecter le code de la route.",
        "Quand je pense à Portal, je me dis que chaque problème a sa solution... et son portail.",
        "Un tour de circuit dans Mario Kart est la meilleure façon de régler nos différents.",
        "L'apocalypse zombie ne me fait pas peur, j'ai survécu à Left 4 Dead.",
        "Mon rêve ? Construire mon propre royaume dans Dragon Quest Builders.",
        "Dans Assassin's Creed, chaque saut de la foi me rappelle qu'il faut parfois prendre des risques.",
        "Chaque session de Tetris me rappelle que parfois, tout s'aligne parfaitement.",
        "L'école de Poudlard dans Harry Potter: Hogwarts Mystery est mon deuxième chez-moi.",
        "Éteindre un feu avec un extincteur dans The Sims, c'est plus stressant que dans la vraie vie.",
        "Voyager entre les mondes dans The Witcher 3 m'a appris que chaque choix a ses conséquences.",
        "Mon entraînement pour les Jeux Olympiques ? Une session de Wii Sports.",
        "Le seul tribunal que je respecte vraiment, c'est celui de Phoenix Wright: Ace Attorney.",
        "Quand je parle de pêche, c'est celle d'Animal Crossing, pas celle de mon oncle.",
        "La seule chose que j'ai vraiment peur de perdre, c'est ma sauvegarde de Dark Souls.",
        "Être un héros dans Overwatch, c'est choisir de ne pas être un zéro.",
        "Quand je vois une étoile filante, je pense à Super Mario et je fais un vœu.",
        "Mon meilleur entraîneur ? Le professeur Oak, évidemment.",
        "Si la vie était comme dans Kingdom Hearts, je chercherais mes amis dans chaque monde.",
        "Ma stratégie de vie ? Inspirée par les échecs tactiques de Fire Emblem.",
        "Rien ne vaut la sensation de frapper un home run dans Wii Sports.",
        "Pour moi, le véritable amour, c'est partager une île sur Animal Crossing.",
        "Se réveiller à côté d'un creeper dans Minecraft n'est jamais bon signe.",
        "La vraie sagesse, c'est savoir combien de rupees économiser pour le prochain bouclier.",
        "Dans le monde de Fallout, chaque Capsule compte plus qu'un dollar.",
        "J'aimerais avoir la capacité de résoudre les problèmes comme dans The Legend of Zelda.",
        "Mon objectif de carrière ? Être un dresseur Pokémon, évidemment.",
        "Le secret du bonheur ? Un inventaire plein.",
        "Si seulement je pouvais utiliser des points de compétence pour améliorer ma vie.",
        "Je ne suis pas perdu, je fais juste une quête secondaire dans la vie.",
        "La clé du succès ? Savoir quand utiliser le turbo dans Mario Kart."
    ]);

    const currentQuote = ref("");

    function generateRandomQuote() {
        const randomIndex = Math.floor(Math.random() * punchlines.value.length);
        currentQuote.value = punchlines.value[randomIndex];
    }

    return {
        currentQuote,
        generateRandomQuote
    };
}
