export enum StatType {
    HOME_PAGE_VISIT = 'HOME_PAGE_VISIT',
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    PHOTO_ANALYSIS = 'PHOTO_ANALYSIS',
    USER_COLLECTION_VISIT = 'USER_COLLECTION_VISIT',
    ADD_NEW_ITEM_VIDEO_GAME = 'ADD_NEW_ITEM_VIDEO_GAME',
    REMOVE_ITEM_VIDEO_GAME = 'REMOVE_ITEM_VIDEO_GAME',
}
